### ISSUE TITLE
Trial expired: show a warning message on upload

### ISSUE THREAD

**Issue by banzo** [koemei/koemei-widget#214]
### Problem

When subscription plan is expired, the user is not notified when his subscription is expired and 

### Steps to reproduce

1. user logs into his expired account
2. user imports a video (from hard drive in this case, need to check how the web app behaves with an url upload)

### Observed behaviour

User is displayed an uninformative error message: 
https://www.dropbox.com/s/w3q3dil09lbiapo/Screenshot%202014-08-07%2018.25.27.png

### Expected behaviour

The user should receive a message informing him that his plan is expired when trying to upload a file with an expired account.

### Resolution pointers

Some of that exception handling is somewhat done (see e.g. ```[shared.service.media] Your subscription plan is expired ```) but is apparently not taken into account in the front end.

### Additional notes

Next steps: 
* users should ne notified when their subscription is expired (and maybe 'about to expire' too): create a periodic task that scans the users
* the web app should display a notification all the time (a top banner e.g.), with a call to action to upgrade

**Comment by vohtaski** [comment]
fixed
