### ISSUE TITLE
Trial expired: show message on Dashboard with Upgrade button

### ISSUE THREAD

**Issue by Temiola** [koemei/koemei-widget#215]
For trial accounts - show #of days left + upgrade now button in the dash board: 
For the moment (until we implement pricing) Upgrade now button would link to our contact form with upgrade header and message.
![image](https://cloud.githubusercontent.com/assets/7411518/3865765/ad45aa00-1fa8-11e4-9ce9-d20c127007aa.png)

**Comment by vohtaski** [comment]
@Temiola I will add message under 'Demo account', there is not enough place on the right.
For now I will only show 'Your free trial is expired', without calculating number of days
+ Upgrade button

**Comment by Temiola** [comment]
Ok that's fine. Tnx

**Comment by vohtaski** [comment]
i did it like this:
![screen shot 2015-02-06 at 16 45 57](https://cloud.githubusercontent.com/assets/158421/6082210/b236b152-ae1f-11e4-9bb5-ef6cb8d74062.png)

**Comment by Temiola** [comment]
The placement / position is where the "organisation name" is, do you think this will not obstruct the name? An option is to make the expire notice smaller after ythe name or on top of the media list?

**Comment by Temiola** [comment]
Here is the screenshot of my suggestion as discussed: 
![image](https://cloud.githubusercontent.com/assets/7411518/6084109/8c3cfb00-ae2e-11e4-8f76-28df1e543436.png)

**Comment by vohtaski** [comment]
fixed
