### ISSUE TITLE
Search Improvement

### ISSUE THREAD

**Issue by Temiola** [koemei/koemei-widget#231]
Improvement areas for search: 
- [x] Global search
first time search is selected for global an error message is displayed. 
If search term is not in videos - same error message is displayed, and sometime search term is in video, and still error message is displayed. 
upon 2nd trial, if search term is in video, search results are displayed.

- [x] Displayed search results. Currently behavior, results from other media from global search does not open the media when the search result is clicked upon; 
Expected behavior: search result in global should open the related media file; replace the middle pane with the related video; replace the left pan with information on the video (of search result) and replace the right pane with the search result from the video page.

- [x] when space is after a search term, search result is broken
- [x] can not search properly search more than key words - search terms should include multiple words or phrase.

**Comment by Temiola** [comment]
the issues #231 seems resolved (except 2nd check box). it looks to me like search is only looking at the "header" of the video. For example search inside the video page widget - under "Global" does not return search results of term present in the transcripts - only return terms that match header

**Comment by vohtaski** [comment]
I implemented 2nd checkbox as well (not on prod yet)
I am closing this issue in favor of this:
https://github.com/koemei/koemei-widget/issues/237
