### ISSUE TITLE
Search issues

### ISSUE THREAD

**Issue by vohtaski** [koemei/koemei-widget#237]
### Koemei Widget 
- [x] No transcript, search does not work

`this.widget.transcript_panel is undefined`

- [ ] Other search issues
it looks to me like search is only looking at the "header" of the video. For example search inside the video page widget - under "Global" does not return search results of term present in the transcripts - only return terms that match header

### This page search:
- [x] Show 'undefined' for query

To reproduce:
#### prod:
query = 'Denise'
notes = 'Hey Denise, are you there?', 'Denise, check this out'
-> undefined undefined

#### local:
query = 'Den'
notes = 'Den, where are you?'
-> undefined undefined
!!!but works with:
query = 'awesome'
notes = 'hohoho, life is awesome'

The problem is when the query is the first word in the notes.

#### prod:
query = 'koemei'
`Error searching videos, please try again later...`
some bugs in the log (probably fixed already with my fix, to be tested)
```
12:06:22,607 ERROR [shared.service.media] Traceback (most recent call last):
  File "/home/tg/www/sites/shared/service/media.py", line 70, in search
    media_item.current_transcript.matches_total = media_match.transcript_matches_total
AttributeError: 'NoneType' object has no attribute 'matches_total'
```
query = 'video'
worked ok

#### local:
query = 'koemei' worked
query = 'test' did not work, errors in console
```
Uncaught TypeError: Cannot read property 'matches' of null
```

**Comment by Temiola** [comment]
I suspect there are multiple search paths, i.e search inside notes; search transcripts; search captions etc. 

Perhaps problem in search notes may be different from search transcript. It may be worth checking.
