### ISSUE TITLE
New search issues

### ISSUE THREAD

**Issue by vohtaski** [koemei/koemei-widget#238]
- [x] multiple test items are not found
I have been testing the search on koemei.com/demo and see the improvements in search. I notice anomalies for example, there are more than 25 videos with “test” in the title - but when I write “test” in the search term - only one video was returned.

**Comment by Temiola** [comment]
Error message on video page: when a search term for example "test" in the video page, and "Global search" is chosen, no result is displayed, but an error message. 
![image](https://cloud.githubusercontent.com/assets/7411518/6057930/d4530aea-ad22-11e4-9728-cc446159b292.png)

**Comment by Temiola** [comment]
Search : Video page > This Page
Search result should be clickable, and video playback should jump to start from time where the word appears;
![image](https://cloud.githubusercontent.com/assets/7411518/6058733/622c4aa0-ad2a-11e4-9cf6-18873b535a49.png)

**Comment by Temiola** [comment]
Search : Video page > Global
Current behavior: 
Clicking on search result video thumbnail > open video page 
Clicking on search result "transcript" > video page is not opened. Sometime move the transcript of current page. 

Expected behavior: 
click on search result opens new video, search term should remain persistent, and search results in transcripts and notes etc. should be displayed for the video; 
click on search result inside transcript should open new video; jump video playback to the time spot of the term in the video timeline. Other results in transcripts / notes are also displayed.

![image](https://cloud.githubusercontent.com/assets/7411518/6058965/db20da82-ad2c-11e4-86be-74375ceca3f7.png)

**Comment by vohtaski** [comment]
@Temiola 
Today we always have to first click on the transcript before seeing it.
The info button does not show anything.

Should I remove info button and always show transcript?

**Comment by Temiola** [comment]
I agree we can remove the "info" button. Make transcript show by default, and if user clicks on the "transcript icon" the transcript window is closed.

**Comment by vohtaski** [comment]
but what is supposed to be in the info button normally? for me it's always empty ..

**Comment by Temiola** [comment]
The info button is suppose to be : video title, date of creation and created by.

**Comment by vohtaski** [comment]
ok, I will disable it for now, in the new widget we will implement the missing parts

**Comment by Temiola** [comment]
It is empty because most of the video in the tests were uploaded through youtube or upload and there was no field to manually input the metadata. If we worked with an organization - the API has a place field to provide metadata.

**Comment by Temiola** [comment]
In the new design, the Title and info is permanent under the video.

**Comment by Temiola** [comment]
you can also remove the button - for smiley - "brilliant and huh" on the right side of the player. And leave only the "comment icon" 
![image](https://cloud.githubusercontent.com/assets/7411518/6104117/0b7034c8-b04b-11e4-8f7c-15a0fea4feb4.png)

**Comment by Temiola** [comment]
I am noticing another strange behaviour in the search - when two or more search terms are input - the result only take into account one search term despite the other search term is in the transcript (in This Page); and in "Global" error is returned: 
![image](https://cloud.githubusercontent.com/assets/7411518/6104205/b95b0c16-b04b-11e4-8049-91349b508eef.png)

![image](https://cloud.githubusercontent.com/assets/7411518/6104238/ed599028-b04b-11e4-8eff-ad0bb122f284.png)

**Comment by Temiola** [comment]
Tried multiple word search on other videos and it worked well... Also worked well in Global. I think I know what is wrong with the other video. It was a video that was shared from "another organization" in Koemei so search may not be well configured for searching global when the video is not really indexed under the user account.. We will not have such scenario in new Koemei.
