### ISSUE TITLE
Search return blank result

### ISSUE THREAD

**Issue by Temiola** [koemei/koemei-widget#245]
I made a search term "test" on koemei.com/demo but the return was zero in Global search despite "test" was present in the media list. Curiously, other search terms in Global seem to work very well. In one of my test, the system return "error".

![image](https://cloud.githubusercontent.com/assets/7411518/6152211/a2606b6a-b21b-11e4-92fb-2a5aa4c36c4a.png)

**Comment by vohtaski** [comment]
there was a small bug, fixed now
